DATA_DIR: './datasets/imdb-clean-master'
EXPERIMENT_NAME: 'single_model'
TRAIN:
  BATCH_SIZE: 5
  LOG_INTERVAL: 2000
  SAVE_INTERVAL: 10000
  STEPS: 100000
  OUTPUT_SIZE: 128, 128
TEST:
  BATCH_SIZE: 5
  OUTPUT_SIZE: 128, 128